name: Block Direct Pushes

on:
  push:
    branches:
      - main
      - stage

jobs:
  block:
    if: github.event_name == 'push' && github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Block Direct Push
        run: |
          echo "â›” Direct push to protected branch is not allowed!" 
          exit 1
